# Generated by Django 5.2.6 on 2025-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_onlyofficesession_filepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='has_multiple_sheets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='last_active_sheet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sheet_count',
            field=models.IntegerField(default=1),
        ),
    ]
