# Generated by Django 5.2.6 on 2025-09-13 11:34

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_has_multiple_sheets_file_last_active_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_onedrive_embed',
            field=models.BooleanField(default=False, help_text='True if this is a OneDrive embed instead of uploaded file'),
        ),
        migrations.AddField(
            model_name='file',
            name='onedrive_direct_link',
            field=models.URLField(blank=True, help_text='Direct OneDrive share link', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='onedrive_embed_url',
            field=models.URLField(blank=True, help_text='OneDrive embed URL for Excel files', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path),
        ),
    ]
